definitions:
  model.TaskModel:
    properties:
      description:
        type: string
      name:
        type: string
      recurring:
        type: boolean
      schedule:
        type: string
    type: object
info:
  contact: {}
paths:
  /tasks/:
    get:
      description: Retrieves all the tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TaskModel'
            type: array
      summary: Fetch all tasks
      tags:
      - tasks
  /tasks/id:
    get:
      description: Retrieves all the tasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TaskModel'
      summary: Fetch all tasks
      tags:
      - tasks
swagger: "2.0"
